CREATE TABLE EMP(
    EMPID CHAR(6) NOT NULL,
    ENAME VARCHAR2(20) NOT NULL,
    DEPT VARCHAR2(20) NOT NULL,
    HIRE_DATE DATE,
    BIRTHDAY VARCHAR2(20),
    ADDRESS VARCHAR2(50),
    JOB VARCHAR2(20),
    SALARY NUMBER(10),
    CONSTRAINT PK_EMP PRIMARY KEY(EMPID)
);

INSERT INTO EMP(EMPID, ENAME, DEPT, HIRE_DATE, BIRTHDAY, ADDRESS, JOB, SALARY)
    VALUES('1006', '장승수', '개발부', SYSDATE, '1985.10.12', '대전 서구 내동 345', 'ERP프로그램', 350); 
INSERT INTO EMP(EMPID, ENAME, DEPT, HIRE_DATE, BIRTHDAY, ADDRESS, JOB, SALARY)
    VALUES('1002', '곽희준', '영업부', SYSDATE, '1985.10.12', '안양 용봉동', '특수영업', 400);
INSERT INTO EMP(EMPID, ENAME, DEPT, HIRE_DATE, BIRTHDAY, ADDRESS, JOB, SALARY)
    VALUES('1003', '김동준', '생산부', SYSDATE, '1985.10.12', '부산 대하동', '품질관리', 300);
INSERT INTO EMP(EMPID, ENAME, DEPT, HIRE_DATE, BIRTHDAY, ADDRESS, JOB, SALARY)
    VALUES('1004', '성재규', '인사부', SYSDATE, '1985.10.12', '대구 달성동', '급여관리', 450);
INSERT INTO EMP(EMPID, ENAME, DEPT, HIRE_DATE, BIRTHDAY, ADDRESS, JOB, SALARY)
    VALUES('1005', '박성범', '구매부', SYSDATE, '1985.10.12', '대전 오류동', '수입자재', 320);

SELECT * FROM EMP;

CREATE VIEW VIEW_EMP1 AS SELECT EMPID, ENAME, DEPT, HIRE_DATE, SALARY FROM EMP;
CREATE VIEW VIEW_EMP2 AS SELECT EMPID, ENAME, DEPT, JOB FROM EMP;
CREATE VIEW VIEW_EMP3 AS SELECT EMPID, ENAME, BIRTHDAY, ADDRESS FROM EMP;

SELECT * FROM VIEW_EMP1;
SELECT * FROM VIEW_EMP2;
SELECT * FROM VIEW_EMP3;

SELECT EMPID FROM VIEW_EMP1 UNION SELECT DEPT FROM VIEW_EMP2;
SELECT EMPID FROM VIEW_EMP1 UNION SELECT ADDRESS FROM EMP;
SELECT EMPID FROM VIEW_EMP1 INTERSECT SELECT EMPID FROM VIEW_EMP2;

SELECT SALARY, A.EMPID, B.ENAME FROM VIEW_EMP1 A,VIEW_EMP2 B;